#####################################################################
# Ben-Porath human capital — life-cycle (Huggett–Ventura–Yaron 2011) #
#####################################################################

# A life-cycle human-capital model. The household block is ONE existing library
# stage — `CapitalInvestmentStage` on a human-capital axis `:h` — with NO bespoke
# household stage rolled here. The whole point of this Part-3 example:
#
#     Household block = CapitalInvestmentStage(:h)
#
# From human capital `h` the agent picks next-period `h'`, paying a convex
# effort cost on gross investment `i = h' − (1−δ)h` and earning the rental flow
# `R·h`. This is the Ben-Porath (1967) technology in the Huggett–Ventura–Yaron
# (2011) life-cycle form: the cross-section over `h` is generated by AGE — agents
# enter young with little human capital, invest heavily early (when the ability
# to produce human capital is high and the horizon is long), and coast later, so
# the marginal distribution over `h` is the hump-shaped life-cycle profile.
#
# Why no shock and no second axis. Ben-Porath's choice is deterministic and the
# policy `h ↦ h'(h)` is monotone, so a stationary infinite-horizon sweep would
# collapse the cross-section to a point mass. The life-cycle (finite-horizon)
# structure is what spreads `h` — and it is also exactly HVY. An ability axis is
# deliberately NOT added: `CapitalInvestmentStage`'s `production`/`effort_cost` are
# `(value; env)` closures that build an `(h', h)` reward with no second-axis dep,
# so a Markov ability state would be economically inert through the stage. The
# age-specific ability PROFILE instead enters through `env` each age — that is
# driver logic (the finite-horizon backward/forward in `steady_state.jl`), not a
# household stage. See `PART3_LITERATURE_MODELS.md` (the human-capital row).
#
# The effort cost is the inverted Ben-Porath production function. New human
# capital `Q = a·(s·h)^γ` from time share `s` at ability `a` ⇒ to deliver gross
# investment `i` the agent forgoes earnings on `s·h = (i/a)^{1/γ}` time, i.e.
#   effort_cost(i; env) = env.R · (i / env.a)^{1/γ}.
# With `γ ∈ (0,1)` this is convex in `i` (exponent `1/γ > 1`), so the reward
# `R·h − effort_cost(h' − (1−δ)h)` is supermodular in `(h', h)` (cross-partial
# `(1−δ)·cost'' ≥ 0`) and `CapitalInvestmentStage`'s `:divide_conquer` monotone solve is
# valid. Higher ability `a` lowers the cost — the engine of the life-cycle.

using HouseholdStages


# Parameters #
#------------#

@kwdef struct HumanCapitalParams
    β       :: Float64 = 0.97                 # patience
    γ       :: Float64 = 0.7                  # Ben-Porath production curvature ∈ (0,1)
    δ       :: Float64 = 0.05                 # human-capital depreciation
    R       :: Float64 = 1.0                  # rental rate of human capital (earnings = R·h)
    a_young :: Float64 = 0.32                 # ability to produce human capital, age 1
    a_old   :: Float64 = 0.04                 # ability at the last working age (tapers ⇒ hump)
    N_age   :: Int     = 40                   # working-life length
    h0      :: Float64 = 2.0                  # human capital at birth (cohort starts here)
    N_h     :: Int     = 250                  # human-capital grid points
    h_min   :: Float64 = 1.0
    h_max   :: Float64 = 35.0
end

Base.Broadcast.broadcastable(p::HumanCapitalParams) = Ref(p)

const human_capital_params = HumanCapitalParams()

"Age-`t` ability (`t = 1…N_age`): a log-linear taper from `a_young` to `a_old` — the
Huggett–Ventura–Yaron declining ability-to-produce-human-capital profile."
function ability_at_age(t::Integer, p = human_capital_params)
    s = (t - 1) / max(p.N_age - 1, 1)
    return exp((1 - s) * log(p.a_young) + s * log(p.a_old))
end


# Household chain assembly — ONE library stage #
#----------------------------------------------#

"""
Build the Ben-Porath human-capital household block — a single library
[`CapitalInvestmentStage`](@ref) on the `:h` axis, with `mean_h = ∫ h dΛ` and
`mean_earnings = ∫ R·h dΛ` attached. No bespoke household stage; the age profile
is threaded through `env` by the finite-horizon driver.
"""
function human_capital_household(p = human_capital_params)
    layout = GriddedLayout(
        :h => GriddedContinuous(p.h_min, p.h_max, p.N_h),
    )

    invest = CapitalInvestmentStage(layout;
        β               = p.β,
        depreciation    = p.δ,
        production      = (h; env) -> env.R * h,
        effort_cost     = (i; env) -> i <= 0 ? 0.0 : env.R * (i / env.a)^(1 / p.γ))
        # defaults: (; axis = :h, monotone_search = :divide_conquer, assume_monotone = false)

    return define_moments!(invest;
        mean_h        = at_end(integrand = :h, reduce = sum),
        mean_earnings = at_end(integrand = (; h, env) -> env.R * h, reduce = sum))
end
